### PR TITLE
Issue#20

### LINKED ISSUE #20: ReplaceText will return TRUE when the string to replace doesn't exist but should
#### Details of the scenario you tried and the problem that is occurring
When attempting to update a configuration file with an entry and that entry doesn't exist yet
Test-TargetResource returns TRUE.  The resource is written in a way that it can only update an entry
in a file if it exists.  I think it would be more useful if the resource could add entries to a configuration 
file as well.
#### Verbose logs showing the problem
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/Desi
redStateConfiguration'.
VERBOSE: An LCM method call arrived from computer 2016-BUILD-1 with user sid S-1-5-21-828028386-903968607-3399198716-500.
VERBOSE: [2016-BUILD-1]: LCM:  [ Start  Set      ]
VERBOSE: [2016-BUILD-1]:                            [DSCEngine] Importing the module C:\Program Files\WindowsPowerShell\Modules\FileContentDsc\1.0.0.38\DscResources\DSR_ReplaceText\DSR_ReplaceText.psm1 in 
force mode.
VERBOSE: [2016-BUILD-1]: LCM:  [ Start  Resource ]  [[ReplaceText]SetTextWithRegex]
VERBOSE: [2016-BUILD-1]: LCM:  [ Start  Test     ]  [[ReplaceText]SetTextWithRegex]
VERBOSE: [2016-BUILD-1]:                            [[ReplaceText]SetTextWithRegex] Importing the module DSR_ReplaceText in force mode.
VERBOSE: [2016-BUILD-1]:                            [[ReplaceText]SetTextWithRegex] Searching using RegEx 'lockPref\("browser.download.dir", ".*"\);' in file 'c:\scratch\firefox.cfg'.
VERBOSE: [2016-BUILD-1]:                            [[ReplaceText]SetTextWithRegex] String not found using RegEx 'lockPref\("browser.download.dir", ".*"\);' in file 'c:\scratch\firefox.cfg', change not req
uired.
VERBOSE: [2016-BUILD-1]: LCM:  [ End    Test     ]  [[ReplaceText]SetTextWithRegex]  in 0.0370 seconds.
VERBOSE: [2016-BUILD-1]: LCM:  [ Skip   Set      ]  [[ReplaceText]SetTextWithRegex]
VERBOSE: [2016-BUILD-1]: LCM:  [ End    Resource ]  [[ReplaceText]SetTextWithRegex]
VERBOSE: [2016-BUILD-1]: LCM:  [ End    Set      ]
VERBOSE: [2016-BUILD-1]: LCM:  [ End    Set      ]    in  0.6480 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.741 seconds

#### Suggested solution to the issue

If Test-TargetResource doesn't find any matches it should return FALSE so it is possible to add additional
entries to a configuration file.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
Configuration Example
{
    Import-DSCResource -ModuleName FileContentDsc

    Node localhost
    {
        ReplaceText SetTextWithRegex
        {
            Path   = 'c:\scratch\firefox.cfg'
            Search = 'lockPref\("browser.download.dir", ".*"\);'
            Type   = 'Text'
            Text   = 'lockPref("browser.download.dir", "N:");'
        }
    }
}
```

#### Version and build of PowerShell the target node is running

PSVersion                      5.1.14393.2155

### PR DESCRIPTION
**Pull request by jcwalker**
#### This Pull Request (PR) fixes the following issues

Fixes #20 
#### Task list

- [ x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ x] Resource documentation added/updated in README.md in resource folder.
- [ x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x ] Comment-based help added/updated.
- [ x] Localization strings added/updated in all localization files as appropriate.
- [x ] Examples appropriately added/updated.
- [ x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/filecontentdsc/21)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Thanks @jcwalker - very much appreciated! I'll review this week.

**Comment by jcwalker** [comment]
___
*[DSCResources/DSR_ReplaceText/DSR_ReplaceText.psm1, line 358 at r4](https://reviewable.io/reviews/plagueho/filecontentdsc/21#-LMC5ASh1t5caEjJexLF:-LMCxXJgEV_9S0Vt2v2S:bug3opj) ([raw file](https://github.com/plagueho/filecontentdsc/blob/aff25a70f5d0ecec568f205fa5e89a60d5cf7cf8/DSCResources/DSR_ReplaceText/DSR_ReplaceText.psm1#L358)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we add some unit tests for this function?
</blockquote></details>

I was thinking how this should be done since there is no logic in the function.  Do I just test for that it returns a sting?  Or do I test that actual output of the function?

**Comment by jcwalker** [comment]
___
*[Tests/Unit/DSR_ReplaceText.Tests.ps1, line 600 at r4](https://reviewable.io/reviews/plagueho/filecontentdsc/21#-LMC55ji35z_Vet_jbhM:-LMD7fQqAgq0OD1hs7T2:bh2xw91) ([raw file](https://github.com/plagueho/filecontentdsc/blob/aff25a70f5d0ecec568f205fa5e89a60d5cf7cf8/Tests/Unit/DSR_ReplaceText.Tests.ps1#L600)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

🤦
</blockquote></details>

Looking at the test I added the tests for this scenario at the top of the describe block

Done.

**Comment by PlagueHO** [comment]
Sorry to take so long @jcwalker - I'll get onto this tomorrow night! It got a bit crazy at work. Just working through my backlog of other reviews as well :grin:

**Comment by nehrua** [comment]
@PlagueHO just checking in on the status of this PR.  I believe I've resolved/acknowledge my comments.  Are there any unresolved comments you require be addressed before merging?

**Pull request merged**
