### PR TITLE
Releasing 1.1.0.0

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

Releasing 1.1.0.0

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/filecontentdsc/24)

### CODE REVIEW

**Comment by johlju** [comment]
The deploy step is not opt-in to.

https://github.com/PlagueHO/FileContentDsc/blob/375ebdc89f921db36922e8c24179bcbbd0902725/appveyor.yml#L40-L41

**Comment by johlju** [comment]
Either change to `-OptIn @('PublishExample')`, or remove `-OptIn @()` to always opt-in to all deploy steps.

https://github.com/PowerShell/DscResource.Tests/blob/02fcc94f54481ff450fc39beb40809956219ad72/AppVeyor.psm1#L1261

**Comment by PlagueHO** [comment]
@johlju - good catch! Doh! Fixed.

**Comment by johlju** [comment]
That didn't work out as expected. 🙂 Is it the wrong key or something else? 🤔

**Comment by PlagueHO** [comment]
Wrong key :grin: I created a key that could only publish FileContentDsc - I needed to make a general key that could be used. But all good now!

https://ci.appveyor.com/project/PlagueHO/filecontentdsc#L1186

So they're all up on the PS Gallery now:
```powershell
Install-Script -Name IniSettingsFile_SetPlainTextEntry_Config 
```

Great work @johlju !!!!

**Comment by PlagueHO** [comment]
I'll begin to work on other resources soon :grin:

**Comment by jcwalker** [comment]
@PlagueHO when is this going to make it to the PSGallery?  I'm still seeing version 1.0.0.38.

**Comment by jcwalker** [comment]
@PlagueHO No worries and thanks for all you do!

**Comment by PlagueHO** [comment]
@jcwalker - a pleasure to support the community and thanks for your help too! :grin:

**Pull request merged**
