### PR TITLE
KeyValuePairFile and ReplaceText: Adds a encoding param - Fixes Issue#5

### PR DESCRIPTION
**Pull request by nehrua**
#### Pull Request (PR) description

This PR Adds an Encoding parameter to both the KeyValuePairFile and ReplaceText resources.

#### This Pull Request (PR) fixes the following issues

- Fixes Issue#5    

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/filecontentdsc/27)

### CODE REVIEW

**Comment by nehrua** [comment]
@PlagueHO thanks for jumping on this so quickly.  Excellent feedback!

**Comment by PlagueHO** [comment]
I'm just about to head away on holiday for a few days so I'll finish the review when I get back on Sunday!

**Comment by nehrua** [comment]
There appears to be an issue with the build.  Its throwing a errors when trying to create and export the self-signed cert.  I was hoping it might timeout, but about 40 mins has passed without a change in status.

**Comment by nehrua** [comment]
We are seeing similar errors on PRs created against the PowerSTIG repo, so this doesn't appear to be related to any code in introduced.  Maybe an issue with, or update to AppVeyor that requires some action on our end to comply?

**Comment by PlagueHO** [comment]
I've kicked the CI again - this was caused by a change made to a PKI module used by DSCResource.Tests (see https://github.com/PowerShell/DscResource.Tests/pull/304). I'll review tomorrow once the tests have passed.

**Comment by nehrua** [comment]
Happy to help @PlagueHO, thanks for your support!

**Pull request merged**
